---
ansible_role_name: chrony
distributions:
  - bionic
readme_note: This role is based on the role ``ansible-hardening`` (https://github.com/openstack/ansible-hardening).
travis_decrypt_key: 854ffc8c95fe
