---
ansible_role_name: chrony
distributions:
  - bionic
  - focal
readme_note: This role is based on the role ``ansible-hardening`` (https://github.com/openstack/ansible-hardening).
travis_decrypt_key: 8437298f293e
